# Copy for both languages. Every key is used by build_lp.py.
COPY['ja'] = dict(
  asset_prefix='', screens_dir='', alt_href='/en/', alt_label='English', tripfy_href='/tripfy/', privacy_href='privacy.html', terms_href='terms.html',
  meta_desc='撮るだけで外国語メニューを日本語に。アレルギー警告、店員に見せる注文票、会計チェック、おすすめ料理まで。14言語・買い切り制・まず5回無料。',
  meta_desc_short='撮るだけでメニューを日本語に。アレルギー警告・注文票・会計チェック対応。14言語・買い切り制。',
  nav_how='使い方', nav_features='機能', nav_new='新機能', nav_pricing='料金', nav_langs='対応言語', nav_faq='よくある質問', nav_cta='アプリを入手', menu_open='メニューを開く',
  sticky_note='無料で5回試せます', dl_sub_ios='Download on the', dl_sub_play='Get it on',
  hero_announce='会計チェックと、店員に見せる注文票が登場',
  hero_title='読めないメニューも、<br>もう怖くない。',
  hero_desc='撮るだけで、料理の名前・説明・値段があなたの言葉に。アレルギーの警告、店員に見せる注文票、会計のチェックまで。旅先の食事の不安を、ぜんぶ引き受けます。',
  hero_cta='無料でダウンロード', meta_langs='14言語', meta_onetime='買い切り・サブスクなし', meta_free='まず5回無料',
  alt_result='Menufyの翻訳結果画面',
  how_lbl='使い方', how_title='撮って、選んで、<em>見せるだけ。</em>', how_desc='複雑な操作はありません。カメラを向けてから、最初の料理が見えるまで数秒です。',
  steps=[('sushi','メニューを撮る','紙でも黒板でもタブレットでも。言語も通貨も自動で判定します。'),
         ('omurice','読んで、選ぶ','料理名・説明・値段があなたの言葉で、1品ずつ順に表示。おすすめや人数別のセットも。'),
         ('ramen','店員に見せる','選んだ料理とアレルギーの申告文が、現地語の注文票に。食後は会計もチェック。')],
  screens_lbl='アプリの画面', screens_title='すべての操作を、<em>数タップで。</em>', screens_desc='設定は言語・通貨・食事制限だけ。あとは撮って、選ぶだけです。', screens_hint='横にスクロール',
  screens=[('01-home.jpg','Menufyのホーム画面','01. 言語と食事制限を登録','言語と通貨は自動判定'),
           ('03-result.jpg','Menufyの翻訳結果画面','02. 翻訳結果が順に届く','おすすめ・警告・食べ方つき'),
           ('04-order.jpg','Menufyの注文票画面','03. 注文票を店員に見せる','アレルギーの申告文も現地語で'),
           ('05-ask.jpg','店員に聞くカード','04. 気になる料理は聞く','「これは入っていますか？」を原語で'),
           ('08-bill.jpg','Menufyの会計チェック画面','05. 会計をチェック','過剰請求や未注文の品を指摘'),
           ('06-paywall.jpg','Menufyの回数券画面','06. 買い切りの回数券','サブスクなし。5回は無料')],
  feat_lbl='機能', feat_title='読むだけで<em>終わらせない。</em>', feat_desc='翻訳のあとに来る「選ぶ・頼む・払う・覚える」まで、ぜんぶ一つのアプリで。',
  features=[('globe','','14言語・自動判定','メニューの言語と通貨を自動で見分けます。設定は翻訳先だけ。'),
            ('coin','butter','為替をその場で換算','現地価格を日本円で表示。一度取ったレートは圏外でも使えます。'),
            ('warn','warn','食事制限アラート','アレルギー・ハラルなど11種類。該当する料理に警告タグを表示し、店員への確認フレーズも用意。'),
            ('hand','','店員に見せる注文票','選んだ料理とアレルギーの申告文を、現地語で全画面に。読み上げもできます。'),
            ('sparkle','butter','この店のおすすめ','メニューから看板料理を3品。1人・2人・4人のセットも提案。辛さ・量・食べ方も。'),
            ('receipt','mint','会計チェック','レシートを撮ると注文と照合。頼んでいない品や高い請求、サービス料を指摘します。'),
            ('fork','mint','食べた記録と旅カード','星と写真で記録。国ごとに1枚のカードにして共有できます。'),
            ('share','','保存・共有・履歴','翻訳結果は画像で保存。履歴は店名や国で検索できます。')],
  why_lbl='なぜ Menufy', why_title='翻訳アプリでは、<em>届かないところへ。</em>', why_desc='文字を置き換えるだけなら、無料の翻訳アプリで足ります。Menufyは「読めた」の先を引き受けます。',
  whys=[('料理単位で理解する','汎用翻訳は文字を訳します。Menufyは<strong>料理を1品ずつ理解</strong>して、名前・説明・値段・警告をひとつのカードにまとめます。'),
        ('安全のために作られている','アレルギーや宗教上の制限を登録すると、<strong>警告タグと店員への確認フレーズ</strong>が付きます。注文票には申告文が自動で載ります。'),
        ('注文と会計まで面倒を見る','<strong>現地語の注文票</strong>で言葉が話せなくても頼めます。食後はレシートを撮るだけで、<strong>請求の間違い</strong>を見つけます。'),
        ('買い切りで、サブスクなし','月額はありません。<strong>必要な分だけ</strong>回数券を買う仕組み。まず5回は無料です。')],
  new_lbl='2026年9月アップデート', new_title='頼むときも、払うときも。<em>もう迷わない。</em>', new_desc='今回の目玉は2つ。会計チェックと、アレルギーを自動で申告する注文票です。',
  nf1_t='会計チェック', nf1_t2='BILL CHECK', nf1_d='食後にレシートを撮ると、<strong>注文した料理とメニューの価格に照らして1行ずつ確認</strong>。頼んでいない品、メニューより高い請求、サービス料や税の内訳を指摘し、店員に聞くための質問文まで用意します。',
  nf1_verdict='合計が合いません', nf1_r1='パッタイ（海老）', nf1_ok='注文と一致', nf1_r2='トムヤムクン', nf1_flag1='メニューより高い（150）', nf1_r3='タイティー', nf1_flag2='注文していない', nf1_r4='サービス料 10%',
  nf2_t='申告文つきの注文票', nf2_t2='POINT-TO-ORDER', nf2_d='選んだ料理を<strong>現地語の注文票</strong>に。設定した食事制限は「私は甲殻類アレルギーです」のように<strong>自動で申告文</strong>になり、票の先頭に載ります。読み上げボタンで発音もできます。',
  nf2_r1='パッタイ（海老）', nf2_r2='カニチャーハン',
  price_lbl='料金', price_title='まず試して、<em>気に入ったら続ける。</em>', price_desc='ダウンロードするだけで5回体験できます。サブスクリプションなし、使いたい分だけ買い切りで。',
  plans=[('Starter Pack','週末旅行に'),('Traveler Pack','長期旅行・移住者に'),('Explorer Pack','海外在住・ヘビーユーザーに')],
  p_feats=lambda n: [f'翻訳と会計チェック {n}回分','為替換算・おすすめ・注文票','翻訳履歴 無制限','保存・共有・旅カード'],
  p_popular='人気', p_unit='回分', p_btn_ios='App Storeで入手', p_btn_play='Google Playで入手',
  p_free_note='ダウンロードするだけで、まず<strong>5回</strong>体験できます。',
  lang_lbl='対応言語', lang_title='世界中のメニューを、<em>翻訳する。</em>', lang_desc='アジアからヨーロッパ、中東まで。メニューの言語は自動で判定します。',
  lang_names=['日本語','英語','中国語（簡体）','中国語（繁体）','韓国語','フランス語','スペイン語','イタリア語','ドイツ語','マレー語','インドネシア語','タイ語','ベトナム語','アラビア語'],
  faq_lbl='よくある質問', faq_title='気になること、<em>ここで解決。</em>',
  faq=[('翻訳の精度はどのくらいですか？','最新のAIを使用しており、印刷メニュー・手書きメニュー・黒板メニュー・タブレット画面など、様々な形式を高精度で翻訳します。料理名だけでなく、原材料や調理法の説明も日本語で表示するので、どんな料理か一目でわかります。'),
       ('オフラインで使えますか？','AI翻訳のため、インターネット接続が必要です。Wi-Fiまたはモバイルデータ通信をご利用ください。一度取得した為替レートは端末に保存され、圏外でも履歴の換算は表示できます。'),
       ('プライバシーは守られますか？','撮影した写真は翻訳処理のみに使用され、サーバーには保存されません。翻訳履歴はお使いの端末本体に保存されます。第三者への販売・共有は一切行いません。'),
       ('サブスクリプションですか？','いいえ、すべて買い切り制です。一度購入したクレジットは有効期限なく使用できます。自動更新のサブスクリプションは一切ありません。'),
       ('購入したクレジットは別の端末でも使えますか？','はい。iOSではiCloud経由で、AndroidではGoogleアカウント経由で、同じアカウントにログインした複数の端末間で自動同期されます。アプリを再インストールしても復元可能です。'),
       ('無料で試せますか？','はい。ダウンロードするだけで、まず5回無料で翻訳をお試しいただけます。気に入ったら、旅行のスタイルに合わせて25回分・150回分・400回分のプランから選べます。'),
       ('アレルギーがあっても使えますか？','設定で食事制限（ベジタリアン・ヴィーガン・ハラル・各種アレルギーなど11種類）を登録すると、該当する可能性のある料理に警告タグが表示され、注文票には申告文が自動で載ります。※AIによる判定のため、重度のアレルギーをお持ちの方は必ず店舗にもご確認ください。'),
       ('言葉が話せなくても注文できますか？','はい。食べたい料理を選ぶと、現地語の定型フレーズと料理名を並べた注文票が全画面で表示されます。店員さんにスマホの画面を見せるだけで注文できます。料理名の発音を読み上げる音声ボタンも利用できます。'),
       ('会計チェックはどう使いますか？','食後にレシートを撮影すると、注文した料理とメニューの価格に照らして1行ずつ確認します。頼んでいない品や高い請求、サービス料・税の内訳を指摘し、店員に聞くための質問文も現地語で用意します。1回につき翻訳1回分のクレジットを使います。'),
       ('メニューの言語や通貨は自分で選ぶ必要がありますか？','いいえ。初期設定では言語も通貨も自動で判定します。判定を固定したいときは、設定で言語や通貨を選ぶと自動判定がオフになります。'),
       ('Google翻訳との違いは？','Menufyはメニューに特化しています。文字を置き換えるのではなく料理を1品ずつ理解し、説明・値段・警告をひとつの画面にまとめます。さらに、おすすめの提案、現地語の注文票、会計チェックまで、「読めた」の先を引き受けます。')],
  faq_new=[('会計チェックはどう使いますか？','食後にレシートを撮影すると、注文した料理とメニューの価格に照らして1行ずつ確認します。頼んでいない品や高い請求、サービス料・税の内訳を指摘し、店員に聞くための質問文も現地語で用意します。'),
           ('メニューの言語や通貨は自分で選ぶ必要がありますか？','いいえ。初期設定では言語も通貨も自動で判定します。判定を固定したいときは、設定で言語や通貨を選ぶと自動判定がオフになります。')],
  t_lbl='ユーザーの声', t_title='世界中の旅人に、<em>愛されている。</em>', t_note='※ 実際のユーザーからご提供いただいた感想です',
  testimonials=[('「マレーシア移住後、ローカル食堂でのご飯がこんなに楽しくなるとは。価格の換算もできるから毎日使ってます」','Yuki T.','🇯🇵 クアラルンプール在住'),
                ('"Finally I can explore Japanese izakayas without stress. The translations are accurate and explain the cooking style too!"','Marco R.','🇮🇹 東京旅行中'),
                ('「タイ旅行中に大活躍。屋台のメニューも読めるから、地元の人が食べてるものと同じものを頼めた」','Kenji M.','🇯🇵 バンコク旅行中')],
  cta_title='次の食事を、<br>もっと楽しく。', cta_desc='まず5回、体験してみてください。<br>気に入ったら、旅のスタイルに合ったプランを選ぶだけ。',
  xp_h='旅行に行くなら、Tripfy も。', xp_sub='予約確認を貼るだけで、AI が旅程を自動作成。同じ開発チームの iOS アプリです。', xp_btn='Tripfy を見る →',
  f_privacy='プライバシーポリシー', f_terms='利用規約',
)

COPY['en'] = dict(
  asset_prefix='../', screens_dir='en/', alt_href='/', alt_label='日本語', tripfy_href='/tripfy/', privacy_href='../privacy.html', terms_href='../terms.html',
  meta_desc='Snap any menu and read it in your language. Allergy alerts, an order card to show staff, a bill check and dish picks. 14 languages, one-time purchase, first 5 scans free.',
  meta_desc_short='Snap a menu, read it in your language. Allergy alerts, order card, bill check. 14 languages, one-time purchase.',
  nav_how='How it works', nav_features='Features', nav_new="What's new", nav_pricing='Pricing', nav_langs='Languages', nav_faq='FAQ', nav_cta='Get the app', menu_open='Open menu',
  sticky_note='First 5 scans are free', dl_sub_ios='Download on the', dl_sub_play='Get it on',
  hero_announce='New: bill check and an order card to show staff',
  hero_title='No menu is scary<br>anymore.',
  hero_desc='Snap a menu and every dish name, description and price appears in your language. Allergy alerts, an order card to show staff, and a check of the bill — everything that makes eating abroad stressful, handled.',
  hero_cta='Download free', meta_langs='14 languages', meta_onetime='One-time purchase, no subscription', meta_free='First 5 scans free',
  alt_result='Menufy translation result screen',
  how_lbl='How it works', how_title='Snap, pick, <em>and show.</em>', how_desc='No setup to speak of. Point the camera and the first dish appears in seconds.',
  steps=[('sushi','Snap the menu','Paper, chalkboard or tablet. The language and currency are detected for you.'),
         ('omurice','Read and pick','Names, descriptions and prices arrive dish by dish, with picks and set suggestions for your party size.'),
         ('ramen','Show the staff','Your dishes and your allergy statements become an order card in the local language. After the meal, check the bill.')],
  screens_lbl='The app', screens_title='Everything, <em>a few taps away.</em>', screens_desc='The only settings are your language, currency and dietary needs. Then it is snap and pick.', screens_hint='Scroll sideways',
  screens=[('01-home.jpg','Menufy home screen','01. Set your language and dietary needs','Menu language and currency are auto-detected'),
           ('03-result.jpg','Menufy result screen','02. Dishes arrive one by one','With picks, warnings and how to eat'),
           ('04-order.jpg','Menufy order card','03. Show the order card','Allergy statements in the local language'),
           ('05-ask.jpg','Ask-staff card','04. Ask about a dish','"Does this contain…?" in the menu\'s language'),
           ('08-bill.jpg','Menufy bill check','05. Check the bill','Overcharges and unordered items flagged'),
           ('06-paywall.jpg','Menufy credit packs','06. One-time credit packs','No subscription. First 5 are free')],
  feat_lbl='Features', feat_title="Reading is <em>only the start.</em>", feat_desc='Choosing, ordering, paying and remembering — all in one app.',
  features=[('globe','','14 languages, auto-detected','The menu\'s language and currency are recognized for you. Only your own language needs setting.'),
            ('coin','butter','Prices in your currency','Live conversion; the last rate keeps working offline.'),
            ('warn','warn','Dietary alerts','11 needs from allergies to halal. Conflicting dishes get a warning tag plus a question to ask the staff.'),
            ('hand','','Order card for staff','Your dishes and allergy statements, full screen, in the local language. Read aloud too.'),
            ('sparkle','butter','Picks for this place','Three dishes worth ordering, plus sets for 1, 2 or 4 people. Spice, portion and how to eat.'),
            ('receipt','mint','Bill check','Photograph the receipt and every line is matched to your order: unordered items, overcharges, service charge.'),
            ('fork','mint','Food log and trip card','Rate dishes with a photo, then share one card per trip.'),
            ('share','','Save, share, history','Save results as an image. Search history by restaurant or country.')],
  why_lbl='Why Menufy', why_title='Where translators <em>stop short.</em>', why_desc='A free translator swaps words. Menufy takes over after "I can read it".',
  whys=[('It understands dishes, not words','General translators translate text. Menufy <strong>understands each dish</strong> and puts name, description, price and warnings on one card.'),
        ('Built for safety','Register allergies or religious needs and you get <strong>warning tags and questions for the staff</strong>. The order card states them for you.'),
        ('It handles ordering and paying','Order without speaking, with a <strong>local-language order card</strong>. After the meal, one photo of the receipt <strong>catches billing mistakes</strong>.'),
        ('Pay once, no subscription','No monthly fee. Buy <strong>only the scans you need</strong>. The first 5 are free.')],
  new_lbl='September 2026 update', new_title='Ordering and paying, <em>without the worry.</em>', new_desc='Two headline features: a bill check, and an order card that states your allergies for you.',
  nf1_t='Bill check', nf1_t2='BILL CHECK', nf1_d='Photograph the receipt after the meal and <strong>every line is checked against your order and the menu prices</strong>. Unordered items, prices above the menu, service charge and tax are explained — with questions to ask the staff.',
  nf1_verdict="Something doesn't add up", nf1_r1='Pad thai (shrimp)', nf1_ok='Matches order', nf1_r2='Tom yum goong', nf1_flag1='Higher than menu (150)', nf1_r3='Thai iced tea', nf1_flag2='Not ordered', nf1_r4='Service charge 10%',
  nf2_t='Order card with your allergies', nf2_t2='POINT-TO-ORDER', nf2_d='Your selected dishes become an <strong>order card in the local language</strong>. Your dietary settings turn into <strong>statements like "I have a shellfish allergy"</strong> at the top of the card, with a speaker button for pronunciation.',
  nf2_r1='Pad thai (shrimp)', nf2_r2='Crab fried rice',
  price_lbl='Pricing', price_title='Try it free.<em> Upgrade if you love it.</em>', price_desc='Download and your first 5 scans are free. No subscription — buy only what you use.',
  plans=[('Starter Pack','For a weekend trip'),('Traveler Pack','For long trips and expats'),('Explorer Pack','For heavy users abroad')],
  p_feats=lambda n: [f'{n} scans, translation or bill check','Currency, picks and order card','Unlimited history','Save, share and trip cards'],
  p_popular='Popular', p_unit='scans', p_btn_ios='Get on App Store', p_btn_play='Get on Google Play',
  p_free_note='Download and try your first <strong>5 scans</strong> free.',
  lang_lbl='Languages', lang_title='Menus from around <em>the world.</em>', lang_desc='From Asia to Europe and the Middle East. The menu\'s language is detected automatically.',
  lang_names=['Japanese','English','Chinese (Simplified)','Chinese (Traditional)','Korean','French','Spanish','Italian','German','Malay','Indonesian','Thai','Vietnamese','Arabic'],
  faq_lbl='FAQ', faq_title='Your questions, <em>answered.</em>',
  faq=[('How accurate is the translation?','Menufy uses the latest AI to deliver high-accuracy translations across printed menus, handwritten menus, chalkboards, and digital tablets. Beyond just dish names, it also explains ingredients and cooking methods so you know exactly what you\'re ordering.'),
       ('Does it work offline?','An internet connection is required for AI translation. Wi-Fi or cellular data both work. The last exchange rate is kept on the device, so history conversions still show offline.'),
       ('Is my privacy protected?','Photos you capture are used only for translation and are never stored on our servers. Translation history is saved on your device. We never sell or share your data with third parties.'),
       ('Is this a subscription?','No — Menufy uses one-time purchases only. Credits you buy never expire, and there are no recurring charges or auto-renewals.'),
       ('Can I use my credits on multiple devices?','Yes. Purchased credits sync automatically — via iCloud on iOS, and via your Google account on Android — so they are shared across all devices signed in with the same account and survive reinstalls.'),
       ('Can I try it for free?','Yes — download the app and your first 5 translations are free. If you like it, choose from 25, 150, or 400 credit packs to match your travel style.'),
       ('Can I use it with food allergies?','Yes. Register your dietary needs (vegetarian, vegan, halal, and common allergies — 11 options) and Menufy flags dishes that may conflict, and states your needs on the order card. Note: flags are AI-generated, so if you have a severe allergy, always confirm with the restaurant as well.'),
       ('Can I order without speaking the language?','Yes. Select the dishes you want and Menufy shows a full-screen order card in the menu\'s own language — a polite request phrase, your allergy statements and your dishes. Just show your phone to the staff. A speaker button pronounces each line.'),
       ('How does the bill check work?','Photograph the receipt after the meal. Every line is checked against your order and the menu prices: unordered items, prices above the menu, and the service charge and tax breakdown are flagged, with questions to ask the staff in the local language. One check uses one scan credit.'),
       ('Do I have to pick the menu language and currency?','No. By default both are detected from the photo. If you want to pin them, choose a language or currency in settings and auto-detect turns off.'),
       ('How is this different from Google Translate?','Menufy is built for menus. Instead of swapping words, it understands each dish and organizes descriptions, prices and warnings on one screen. Then it goes further: picks, an order card in the local language, and a bill check.')],
  faq_new=[('How does the bill check work?','Photograph the receipt after the meal. Every line is checked against your order and the menu prices: unordered items, prices above the menu, and the service charge and tax breakdown are flagged, with questions to ask the staff in the local language.'),
           ('Do I have to pick the menu language and currency?','No. By default both are detected from the photo. If you want to pin them, choose a language or currency in settings and auto-detect turns off.')],
  t_lbl='Testimonials', t_title='Loved by travelers <em>around the world.</em>', t_note='※ Real quotes from actual users',
  testimonials=[('"After moving to Malaysia, local eateries finally make sense. Being able to convert prices on the spot is a game changer — I use it every day."','Yuki T.','🇯🇵 Kuala Lumpur, resident'),
                ('"Finally I can explore Japanese izakayas without stress. The translations are accurate and explain the cooking style too!"','Marco R.','🇮🇹 Visiting Tokyo'),
                ('"Saved me during my Thailand trip. Street food menus are suddenly readable — I could order exactly what the locals were eating."','Kenji M.','🇯🇵 Visiting Bangkok')],
  cta_title='Make your next meal<br>a little more fun.', cta_desc='Start with 5 free scans.<br>If you love it, pick a pack that fits your trip.',
  xp_h='Traveling? Try Tripfy too.', xp_sub='Paste your booking confirmations and AI builds your itinerary. From the same team, on iOS.', xp_btn='See Tripfy →',
  f_privacy='Privacy Policy', f_terms='Terms',
)
